# Generated by Django 4.2.13 on 2024-06-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_album_categoria_foto_remove_photo_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField()),
                ('url_shortened', models.CharField(blank=True, max_length=350, unique=True)),
                ('album_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_shortened', to='gallery.album')),
            ],
        ),
    ]
