# Generated by Django 4.2.13 on 2024-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_urlshortener'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField()),
                ('album_name', models.CharField(blank=True, max_length=350, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='URLShortener',
        ),
    ]
