# Generated by Django 4.2.13 on 2024-06-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_customurl_delete_urlshortener'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomURL',
        ),
    ]
